name: CI  # 工作流名稱

on: [push]  # 觸發條件：每當有代碼推送時觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 設置運行環境：最新的 Ubuntu

    steps:
    - uses: actions/checkout@v2  # 步驟1：檢出最新的代碼
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 步驟2：設置 Node.js 環境，使用版本16
    - run: npm install  # 步驟3：安裝依賴
    - run: npm test  # 步驟4：運行測試
